name: Create base release

on:
  workflow_call:
    inputs:
      bump_version:
        description: 'The bump release'
        type: string
        required: true
        default: 'false'

jobs:
  init-release-data:
    name: Generate data about the release
    runs-on: ubuntu-latest
    steps:
      - name: Setup a new Semantic Version
        id: new_semantic_setup
        uses: zwaldowski/semver-release-action@v2
        with:
          bump: ${{ inputs.bump_version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
